export const API_BASE = '/api/v1'

export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: `${API_BASE}/auth/login`,
    REGISTER: `${API_BASE}/auth/register`,
    LOGOUT: `${API_BASE}/auth/logout`,
    ME: `${API_BASE}/auth/me`,
    SETTINGS: `${API_BASE}/auth/settings`,
    FORGOT_PASSWORD: `${API_BASE}/auth/forgot-password`,
    RESET_PASSWORD: `${API_BASE}/auth/reset-password`,
    RESET_DATA: `${API_BASE}/auth/reset-data`,
  },
  TASKS: {
    BASE: `${API_BASE}/tasks`,
    DETAIL: (id: string) => `${API_BASE}/tasks/${id}`,
    ARCHIVE: (id: string) => `${API_BASE}/tasks/${id}/archive`,
    REORDER: `${API_BASE}/tasks/reorder`,
    RECURRENCE_HISTORY: (id: string) => `${API_BASE}/tasks/${id}/recurrence-history`,
    SUBTASKS: (taskId: string) => `${API_BASE}/tasks/${taskId}/subtasks`,
    SUBTASK_DETAIL: (taskId: string, id: string) =>
      `${API_BASE}/tasks/${taskId}/subtasks/${id}`,
    LABELS: `${API_BASE}/task-labels`,
    LABEL_DETAIL: (id: string) => `${API_BASE}/task-labels/${id}`,
  },
  TASK_LISTS: {
    BASE: `${API_BASE}/task-lists`,
    DETAIL: (id: string) => `${API_BASE}/task-lists/${id}`,
  },
  TASK_TAGS: {
    BASE: `${API_BASE}/task-tags`,
    DETAIL: (id: string) => `${API_BASE}/task-tags/${id}`,
  },
  HABITS: {
    BASE: `${API_BASE}/habits`,
    DETAIL: (id: string) => `${API_BASE}/habits/${id}`,
    LOG: (id: string) => `${API_BASE}/habits/${id}/log`,
    UNLOG: (id: string) => `${API_BASE}/habits/${id}/log`,
    ARCHIVE: (id: string) => `${API_BASE}/habits/${id}/archive`,
    UNARCHIVE: (id: string) => `${API_BASE}/habits/${id}/unarchive`,
    STATS: (id: string) => `${API_BASE}/habits/${id}/stats`,
    HEATMAP: (id: string) => `${API_BASE}/habits/${id}/heatmap`,
    TODAY: `${API_BASE}/habits/today`,
  },
  FINANCE: {
    ACCOUNTS: `${API_BASE}/finance/accounts`,
    ACCOUNT_DETAIL: (id: string) => `${API_BASE}/finance/accounts/${id}`,
    CARDS: `${API_BASE}/finance/cards`,
    CARD_DETAIL: (id: string) => `${API_BASE}/finance/cards/${id}`,
    TRANSACTIONS: `${API_BASE}/finance/transactions`,
    TRANSACTION_DETAIL: (id: string) => `${API_BASE}/finance/transactions/${id}`,
    CATEGORIES: `${API_BASE}/finance/categories`,
    CATEGORY_DETAIL: (id: string) => `${API_BASE}/finance/categories/${id}`,
    TAGS: `${API_BASE}/finance/tags`,
    TAG_DETAIL: (id: string) => `${API_BASE}/finance/tags/${id}`,
    BALANCE_HISTORICAL: `${API_BASE}/finance/balance/historical`,
    REPORTS: `${API_BASE}/finance/reports`,
    REPORTS_MONTHLY: `${API_BASE}/finance/reports/monthly`,
    REPORTS_YEARLY: `${API_BASE}/finance/reports/yearly`,
    REPORTS_CASHFLOW: `${API_BASE}/finance/reports/cashflow`,
    REPORTS_BALANCE: `${API_BASE}/finance/reports/balance`,
    BUDGETS: `${API_BASE}/finance/budgets`,
    BUDGET_DETAIL: (id: string) => `${API_BASE}/finance/budgets/${id}`,
    BUDGET_PREVIOUS: `${API_BASE}/finance/budgets/previous`,
    FINANCE_GOALS: `${API_BASE}/finance/goals`,
    FINANCE_GOAL_DETAIL: (id: string) => `${API_BASE}/finance/goals/${id}`,
    FINANCE_GOAL_COMPLETE: (id: string) => `${API_BASE}/finance/goals/${id}/complete`,
  },
  REPORTS: {
    HABITS_LOG_COUNT: `${API_BASE}/reports/habits-log-count`,
    WEEKLY_PRODUCTIVITY: `${API_BASE}/reports/weekly-productivity`,
  },
  GOALS: {
    BASE: `${API_BASE}/goals`,
    DETAIL: (id: string) => `${API_BASE}/goals/${id}`,
    PROGRESS: (id: string) => `${API_BASE}/goals/${id}/progress`,
  },
  CALENDAR: {
    BASE: `${API_BASE}/calendar`,
    DETAIL: (id: string) => `${API_BASE}/calendar/${id}`,
    UPCOMING: `${API_BASE}/calendar/upcoming`,
  },
  DASHBOARD: `${API_BASE}/dashboard`,
  PURCHASES: {
    BASE: `${API_BASE}/purchases`,
    DETAIL: (id: string) => `${API_BASE}/purchases/${id}`,
  },
  SHOPPING: {
    SESSIONS: `${API_BASE}/shopping/sessions`,
    SESSION_DETAIL: (id: string) => `${API_BASE}/shopping/sessions/${id}`,
    SESSION_FINISH: (id: string) => `${API_BASE}/shopping/sessions/${id}/finish`,
    SESSION_REOPEN: (id: string) => `${API_BASE}/shopping/sessions/${id}/reopen`,
    SESSION_ITEMS: (sessionId: string) => `${API_BASE}/shopping/sessions/${sessionId}/items`,
    ITEM_DETAIL: (id: string) => `${API_BASE}/shopping/items/${id}`,
  },
  BOOKMARKS: {
    COLLECTIONS: `${API_BASE}/bookmarks/collections`,
    COLLECTION_DETAIL: (id: string) => `${API_BASE}/bookmarks/collections/${id}`,
    COLLECTIONS_REORDER: `${API_BASE}/bookmarks/collections/reorder`,
    LINKS: (collectionId: string) => `${API_BASE}/bookmarks/collections/${collectionId}/links`,
    LINKS_REORDER: (collectionId: string) => `${API_BASE}/bookmarks/collections/${collectionId}/links/reorder`,
    LINK_DETAIL: (id: string) => `${API_BASE}/bookmarks/links/${id}`,
    LINK_FAVORITE: (id: string) => `${API_BASE}/bookmarks/links/${id}/favorite`,
  },
  PRICES: {
    CATEGORIES: `${API_BASE}/prices/categories`,
    CATEGORY_DETAIL: (id: string) => `${API_BASE}/prices/categories/${id}`,
    STORES: `${API_BASE}/prices/stores`,
    STORE_DETAIL: (id: string) => `${API_BASE}/prices/stores/${id}`,
    PRODUCTS: `${API_BASE}/prices/products`,
    PRODUCT_DETAIL: (id: string) => `${API_BASE}/prices/products/${id}`,
    PRICE_RECORDS: `${API_BASE}/prices/price-records`,
    PRICE_RECORD_DETAIL: (id: string) => `${API_BASE}/prices/price-records/${id}`,
    PURCHASES: `${API_BASE}/prices/purchases`,
    PURCHASE_DETAIL: (id: string) => `${API_BASE}/prices/purchases/${id}`,
    SALES: `${API_BASE}/prices/sales`,
    SALE_DETAIL: (id: string) => `${API_BASE}/prices/sales/${id}`,
    DASHBOARD: `${API_BASE}/prices/dashboard`,
    PRICE_HISTORY: (id: string) => `${API_BASE}/prices/products/${id}/price-history`,
    COMPARE: `${API_BASE}/prices/compare`,
    PATRIMONY: `${API_BASE}/prices/patrimony`,
  },
  NOTES: {
    BASE: `${API_BASE}/notes`,
    DETAIL: (id: string) => `${API_BASE}/notes/${id}`,
    PIN: (id: string) => `${API_BASE}/notes/${id}/pin`,
    FAVORITE: (id: string) => `${API_BASE}/notes/${id}/favorite`,
    ARCHIVE: (id: string) => `${API_BASE}/notes/${id}/archive`,
    UNARCHIVE: (id: string) => `${API_BASE}/notes/${id}/unarchive`,
    TAGS: `${API_BASE}/note-tags`,
    TAG_DETAIL: (id: string) => `${API_BASE}/note-tags/${id}`,
  },
} as const
